### ISSUE TITLE
Missing "services" section when node offline

### ISSUE THREAD

**Issue by dchandan** [DACCS-Climate/Marble-node-registry#37]
The recent brief shutdown of PAVICS has related an issue that break the whole `marble_client`. When a node is offline the node data does not contain the services section, so creating a `MarbleClient` connection fails with the following error:

```
File ~/DACCS/Codes/marble_client_python/marble_client/client.py:66, in MarbleClient.__init__(self, fallback)
     63     self._load_registry_from_cloud(registry)
     65 for node, node_details in self._registry.items():
---> 66     self._nodes[node] = MarbleNode(node, node_details)

File ~/DACCS/Codes/marble_client_python/marble_client/node.py:25, in MarbleNode.__init__(self, nodename, jsondata)
     21 self._services: list[str] = []
     23 __import__("IPython").embed()
---> 25 for service in jsondata["services"]:
     26     s = MarbleService(service)
     27     setattr(self, s.name, s)

KeyError: 'services'
```

This, of course happens when parsing the node that is offline, other node's data are OK. With this issue, basically anytime a node is offline a client cannot be created. This is not desirable.

A simple solution would be to enclose the step where a node's services are created in the `MarbleNode` constructor within an if condition as follows:

```
        if jsondata["status"] != "offline":
            for service in jsondata["services"]:
                s = MarbleService(service)
                setattr(self, s.name, s)
                self._services.append(s.name)
```

In this case if a node `mynode` is offline, querying `mynode.services` gives an empty list.

However, I think a better solution would be to ensure that if a node is offline and its services endpoint can't be queried, then its services information is populated with some cached information. This way the information about the services are still shown, which I think makes sense, but the service URLs will not function because the node is offline. But this solution require a bit of extra engineering and design decisions to make sure that we keep some cached version that is "complete"  in the sense that it contains information that might not be obtainable if a node is offline.

In the meantime I'll make a PR with the aforementioned fix to ensure that the marble client continues to function in the event of a node going offline.

**Comment by dchandan** [comment]
Fix for this in marble_client https://github.com/DACCS-Climate/marble_client_python/pull/19

**Comment by mishaschwartz** [comment]
> However, I think a better solution would be to ensure that if a node is offline and its services endpoint can't be queried, then its services information is populated with some cached information

I'm not sure about this. If a node is offline, then none of its services are available. If none of its services are available then they shouldn't be included in the services list for that node. We don't include status information for individual services in this registry.

Also, the services key was intentionally left out of the required arguments in the schema:

https://github.com/DACCS-Climate/Marble-node-registry/blob/7fc410a0fa545c11540805db0adf2d7ad576fbf6/node_registry.schema.json#L169-L175

I think the proper solution is to fix the python client but to leave this as is. The expected behaviour is defined in the schema (ie. services is not a required key) so the client should not expect it to be present at all times.

**Comment by mishaschwartz** [comment]
Resolved by https://github.com/DACCS-Climate/marble_client_python/pull/19
